// Curated exercise library.
// Images are sourced from yuhonas/free-exercise-db (Unlicense / public domain)
// via jsDelivr CDN. If an image URL 404s the UI falls back to a styled tile.
//
// Each exercise has:
//   id          - stable kebab-case identifier
//   name        - display name
//   muscle      - primary muscle group (back | chest | shoulders | legs | arms | core | cardio | full)
//   equipment   - barbell | dumbbell | cable | machine | bodyweight | bands | kettlebell
//   defaultSets - sensible default for the builder
//   instructions - 2-4 short steps
//   image       - public-domain image URL (free-exercise-db) or null

const cdn = (folder, n = 0) =>
  `https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/${folder}/${n}.jpg`;

export const EXERCISES = [
  // ──────────── BACK ────────────
  { id: 'rack-pull', name: 'Rack pull', muscle: 'back', equipment: 'barbell', defaultSets: 4,
    instructions: ['Set bar in rack just below knees', 'Drive hips forward, squeeze lats at the top', 'Lower under control to the pins'],
    image: cdn('Rack_Pulls') },
  { id: 'deadlift', name: 'Conventional deadlift', muscle: 'back', equipment: 'barbell', defaultSets: 4,
    instructions: ['Bar over mid-foot, brace core', 'Push the floor away, hips and shoulders rise together', 'Lock out tall, do not hyperextend'],
    image: cdn('Barbell_Deadlift') },
  { id: 'bent-row', name: 'Bent-over barbell row', muscle: 'back', equipment: 'barbell', defaultSets: 3,
    instructions: ['Hinge to ~45°, neutral spine', 'Pull bar to lower ribs', 'Squeeze the back, lower with control'],
    image: cdn('Bent_Over_Barbell_Row') },
  { id: 'pendlay-row', name: 'Pendlay row', muscle: 'back', equipment: 'barbell', defaultSets: 3,
    instructions: ['Each rep starts dead-stop on the floor', 'Explosive pull to sternum', 'Reset between reps'],
    image: null },
  { id: 'pullup', name: 'Pull-ups', muscle: 'back', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Dead hang, shoulders packed', 'Drive elbows down, chin over bar', 'Lower fully'],
    image: cdn('Pullups') },
  { id: 'lat-pulldown', name: 'Lat pulldown', muscle: 'back', equipment: 'cable', defaultSets: 3,
    instructions: ['Wider than shoulder grip, lean back ~10°', 'Pull bar to upper chest', 'Control the eccentric'],
    image: cdn('Wide-Grip_Lat_Pulldown') },
  { id: 'seated-row', name: 'Seated cable row', muscle: 'back', equipment: 'cable', defaultSets: 3,
    instructions: ['Tall chest, slight backward lean', 'Drive elbows past torso', 'Squeeze shoulder blades'],
    image: cdn('Seated_Cable_Rows') },
  { id: 'one-arm-row', name: 'One-arm dumbbell row', muscle: 'back', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Knee on bench, flat back', 'Row dumbbell to hip', 'Slow eccentric'],
    image: cdn('One-Arm_Dumbbell_Row') },
  { id: 'lat-pullover', name: 'Cable lat pullover', muscle: 'back', equipment: 'cable', defaultSets: 3,
    instructions: ['Stand back from high pulley, slight hinge', 'Drive bar/rope down with straight arms', 'Stretch and squeeze lats'],
    image: cdn('Straight-Arm_Pulldown') },
  { id: 'face-pull', name: 'Face pull', muscle: 'back', equipment: 'cable', defaultSets: 3,
    instructions: ['High pulley, rope', 'Pull rope to forehead, elbows high', 'External rotation at the end'],
    image: cdn('Face_Pull') },

  // ──────────── CHEST ────────────
  { id: 'bench', name: 'Barbell bench press', muscle: 'chest', equipment: 'barbell', defaultSets: 4,
    instructions: ['Tight upper back, feet planted', 'Lower bar to lower chest', 'Press up and slightly back'],
    image: cdn('Barbell_Bench_Press_-_Medium_Grip') },
  { id: 'incline-bench', name: 'Incline barbell press', muscle: 'chest', equipment: 'barbell', defaultSets: 4,
    instructions: ['Bench at ~30°', 'Lower to upper chest', 'Drive bar straight up'],
    image: cdn('Barbell_Incline_Bench_Press_-_Medium_Grip') },
  { id: 'db-bench', name: 'Dumbbell bench press', muscle: 'chest', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Dumbbells just outside chest', 'Press up, slight inward arc', 'Stretch at the bottom'],
    image: cdn('Dumbbell_Bench_Press') },
  { id: 'incline-db', name: 'Incline dumbbell press', muscle: 'chest', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Bench at 30°', 'Press up and slightly together', 'Control the descent'],
    image: cdn('Incline_Dumbbell_Press') },
  { id: 'fly', name: 'Cable fly', muscle: 'chest', equipment: 'cable', defaultSets: 3,
    instructions: ['Slight bend in elbows held throughout', 'Bring hands together in front', 'Big stretch on the way out'],
    image: cdn('Cable_Crossover') },
  { id: 'db-fly', name: 'Dumbbell fly', muscle: 'chest', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Slight elbow bend', 'Open arms wide, deep stretch', 'Squeeze chest at top'],
    image: cdn('Dumbbell_Flyes') },
  { id: 'pushup', name: 'Push-ups', muscle: 'chest', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Body in a straight line', 'Lower until chest grazes floor', 'Press up explosively'],
    image: cdn('Pushups') },
  { id: 'weighted-pushup', name: 'Weighted push-ups', muscle: 'chest', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Plate on upper back held by partner / strap', 'Same form as a regular push-up', 'Tempo: 2 down, 1 up'],
    image: cdn('Pushups') },
  { id: 'dips', name: 'Chest dips', muscle: 'chest', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Lean torso forward', 'Lower until shoulders are below elbows', 'Press to lockout'],
    image: cdn('Dips_-_Chest_Version') },

  // ──────────── SHOULDERS ────────────
  { id: 'ohp', name: 'Overhead press', muscle: 'shoulders', equipment: 'barbell', defaultSets: 4,
    instructions: ['Bar at collar height, glutes tight', 'Press straight overhead, head through window', 'Lower under control'],
    image: cdn('Standing_Military_Press') },
  { id: 'db-shoulder', name: 'Dumbbell shoulder press', muscle: 'shoulders', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Seat upright, dumbbells at ear height', 'Press to lockout', 'Slow eccentric'],
    image: cdn('Seated_Dumbbell_Press') },
  { id: 'lateral', name: 'Lateral raise', muscle: 'shoulders', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Soft elbow, slight forward lean', 'Lead with the elbows', 'Stop at shoulder height'],
    image: cdn('Side_Lateral_Raise') },
  { id: 'front-raise', name: 'Front raise', muscle: 'shoulders', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Alternate or both arms', 'Raise to eye level', 'Lower with control'],
    image: cdn('Front_Dumbbell_Raise') },
  { id: 'rear-delt-fly', name: 'Rear delt fly', muscle: 'shoulders', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Hinge to 45°', 'Wide arc, drive elbows back', 'Squeeze rear delts'],
    image: cdn('Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench') },
  { id: 'shrug', name: 'Barbell shrug', muscle: 'shoulders', equipment: 'barbell', defaultSets: 3,
    instructions: ['Bar in front, arms straight', 'Shrug straight up to ears', 'Hold at top'],
    image: cdn('Barbell_Shrug') },
  { id: 'arnold', name: 'Arnold press', muscle: 'shoulders', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Start with palms facing you', 'Rotate as you press up', 'Reverse on the way down'],
    image: cdn('Arnold_Dumbbell_Press') },

  // ──────────── LEGS ────────────
  { id: 'squat', name: 'Barbell back squat', muscle: 'legs', equipment: 'barbell', defaultSets: 4,
    instructions: ['Bar across upper traps, brace', 'Sit between hips, knees track over toes', 'Drive up through mid-foot'],
    image: cdn('Barbell_Squat') },
  { id: 'front-squat', name: 'Front squat', muscle: 'legs', equipment: 'barbell', defaultSets: 3,
    instructions: ['Bar in front rack, elbows high', 'Stay tall through the hole', 'Drive elbows up out of the bottom'],
    image: cdn('Front_Barbell_Squat') },
  { id: 'rdl', name: 'Romanian deadlift', muscle: 'legs', equipment: 'barbell', defaultSets: 3,
    instructions: ['Soft knees, hinge at hips', 'Bar travels close to legs', 'Stretch hamstrings, drive hips through'],
    image: cdn('Romanian_Deadlift') },
  { id: 'leg-press', name: 'Leg press', muscle: 'legs', equipment: 'machine', defaultSets: 3,
    instructions: ['Feet shoulder-width on platform', 'Lower until thighs near chest', 'Press without locking knees'],
    image: cdn('Leg_Press') },
  { id: 'leg-ext', name: 'Leg extension', muscle: 'legs', equipment: 'machine', defaultSets: 4,
    instructions: ['Pad on lower shin', 'Extend fully, brief hold', 'Slow eccentric'],
    image: cdn('Leg_Extensions') },
  { id: 'leg-curl', name: 'Leg curl', muscle: 'legs', equipment: 'machine', defaultSets: 3,
    instructions: ['Hips locked, lats engaged', 'Curl heels toward glutes', 'Resist on the way down'],
    image: cdn('Lying_Leg_Curls') },
  { id: 'walking-lunge', name: 'Walking lunge', muscle: 'legs', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Long step, knee tracks over toe', 'Drop the back knee just off the floor', 'Drive forward, repeat'],
    image: cdn('Dumbbell_Lunges') },
  { id: 'bulgarian', name: 'Bulgarian split squat', muscle: 'legs', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Rear foot on bench', 'Drop straight down', 'Drive through front heel'],
    image: cdn('Dumbbell_Squat_To_A_Bench') },
  { id: 'calf-raise', name: 'Standing calf raise', muscle: 'legs', equipment: 'machine', defaultSets: 3,
    instructions: ['Ball of foot on edge', 'Drive up onto big toes', 'Long stretch at the bottom'],
    image: cdn('Standing_Calf_Raises') },
  { id: 'hip-thrust', name: 'Hip thrust', muscle: 'legs', equipment: 'barbell', defaultSets: 3,
    instructions: ['Upper back on bench, bar over hips', 'Drive hips up, ribs down', 'Squeeze glutes hard at top'],
    image: cdn('Barbell_Hip_Thrust') },

  // ──────────── ARMS ────────────
  { id: 'cgbp', name: 'Close-grip bench press', muscle: 'arms', equipment: 'barbell', defaultSets: 4,
    instructions: ['Hands shoulder-width', 'Elbows tucked, lower to lower chest', 'Press straight up'],
    image: cdn('Close-Grip_Barbell_Bench_Press') },
  { id: 'skull', name: 'Skull crusher', muscle: 'arms', equipment: 'barbell', defaultSets: 3,
    instructions: ['EZ bar overhead', 'Lower to forehead, elbows fixed', 'Extend explosively'],
    image: cdn('EZ-Bar_Skullcrusher') },
  { id: 'tri-pushdown', name: 'Triceps pushdown', muscle: 'arms', equipment: 'cable', defaultSets: 3,
    instructions: ['Elbows pinned at sides', 'Extend fully, squeeze triceps', 'Slow return'],
    image: cdn('Triceps_Pushdown') },
  { id: 'overhead-tri', name: 'Overhead triceps extension', muscle: 'arms', equipment: 'cable', defaultSets: 3,
    instructions: ['Rope or bar, lean forward slightly', 'Stretch the long head', 'Extend fully overhead'],
    image: cdn('Overhead_Cable_Curl') },
  { id: 'bicep-curl', name: 'Barbell curl', muscle: 'arms', equipment: 'barbell', defaultSets: 3,
    instructions: ['Elbows at sides', 'Curl without swinging', 'Squeeze at the top'],
    image: cdn('Barbell_Curl') },
  { id: 'db-curl', name: 'Dumbbell curl', muscle: 'arms', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Supinate as you curl', 'No elbow drift', 'Slow eccentric'],
    image: cdn('Dumbbell_Bicep_Curl') },
  { id: 'hammer', name: 'Hammer curl', muscle: 'arms', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Neutral grip throughout', 'Curl up, brief hold', 'Lower under control'],
    image: cdn('Hammer_Curls') },
  { id: 'preacher', name: 'Preacher curl', muscle: 'arms', equipment: 'barbell', defaultSets: 3,
    instructions: ['Armpits on top of pad', 'Lower fully under control', 'Curl without lifting elbows'],
    image: cdn('Preacher_Curl') },
  { id: 'reverse-curl', name: 'Reverse curl', muscle: 'arms', equipment: 'barbell', defaultSets: 2,
    instructions: ['Pronated grip', 'Curl up, hold at the top', 'Slow eccentric'],
    image: cdn('Reverse_Barbell_Curl') },
  { id: 'wrist-curl', name: 'Wrist curl', muscle: 'arms', equipment: 'dumbbell', defaultSets: 3,
    instructions: ['Forearms on knees, palms up', 'Let weight roll to fingertips', 'Curl back up'],
    image: cdn('Seated_Dumbbell_Palms-Up_Wrist_Curl') },

  // ──────────── CORE ────────────
  { id: 'plank', name: 'Plank', muscle: 'core', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Forearms on ground, body straight', 'Squeeze glutes and quads', 'Hold for time'],
    image: cdn('Plank') },
  { id: 'hanging-knee-raise', name: 'Hanging knee raise', muscle: 'core', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Active hang, shoulders down', 'Curl knees toward chest', 'Lower without swinging'],
    image: cdn('Hanging_Leg_Raise') },
  { id: 'crunch', name: 'Crunch', muscle: 'core', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Lower back stays planted', 'Curl shoulders off the floor', 'Squeeze, then lower'],
    image: cdn('Crunches') },
  { id: 'cable-crunch', name: 'Cable crunch', muscle: 'core', equipment: 'cable', defaultSets: 3,
    instructions: ['Kneel under high pulley', 'Curl down with abs only', 'Resist the return'],
    image: cdn('Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists') },
  { id: 'russian-twist', name: 'Russian twist', muscle: 'core', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Lean back ~45°', 'Twist torso side to side', 'Touch the floor lightly each rep'],
    image: cdn('Cross-Body_Crunch') },
  { id: 'ab-wheel', name: 'Ab rollout', muscle: 'core', equipment: 'bodyweight', defaultSets: 3,
    instructions: ['Rounded back, hollow body', 'Roll out as far as you can hold', 'Pull back with your abs'],
    image: cdn('Ab_Roller') },

  // ──────────── CARDIO ────────────
  { id: 'rower', name: 'Rowing machine', muscle: 'cardio', equipment: 'machine', defaultSets: 1,
    instructions: ['Drive with legs first', 'Then hips, then arms', 'Reverse on the recovery'],
    image: cdn('Rowing_Stationary') },
  { id: 'treadmill', name: 'Treadmill (steady-state)', muscle: 'cardio', equipment: 'machine', defaultSets: 1,
    instructions: ['Warm up 3 minutes', 'Hold conversational pace 20-40 min', 'Cool down 3 minutes'],
    image: null },
  { id: 'hiit-bike', name: 'HIIT bike sprints', muscle: 'cardio', equipment: 'machine', defaultSets: 8,
    instructions: ['30 sec all-out, 60 sec easy', 'Repeat 6-10 rounds', 'Cool down 5 min'],
    image: null },
  { id: 'jump-rope', name: 'Jump rope', muscle: 'cardio', equipment: 'bodyweight', defaultSets: 5,
    instructions: ['Light bounce, soft knees', 'Wrists turn the rope', '60 seconds on, 30 off'],
    image: null },
];

export const MUSCLE_GROUPS = [
  { id: 'all', label: 'All' },
  { id: 'back', label: 'Back' },
  { id: 'chest', label: 'Chest' },
  { id: 'shoulders', label: 'Shoulders' },
  { id: 'legs', label: 'Legs' },
  { id: 'arms', label: 'Arms' },
  { id: 'core', label: 'Core' },
  { id: 'cardio', label: 'Cardio' },
];

export const MUSCLE_ACCENTS = {
  back: { hue: 220, label: 'Back' },
  chest: { hue: 0, label: 'Chest' },
  shoulders: { hue: 280, label: 'Shoulders' },
  legs: { hue: 140, label: 'Legs' },
  arms: { hue: 30, label: 'Arms' },
  core: { hue: 50, label: 'Core' },
  cardio: { hue: 190, label: 'Cardio' },
  full: { hue: 250, label: 'Full body' },
};

export function exerciseById(id) {
  return EXERCISES.find((e) => e.id === id) || null;
}
